spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/order_service
    user: root
    password: 1234

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8085

server:
  port: 8081

logging:
  level:
    root: INFO
    org.apache.kafka: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

inventory:
  url: http://localhost:8082
